### ISSUE TITLE
valueForKeyPath returns undefined when value is 0

### ISSUE THREAD

**Issue by davidmontoyago** [jeeeyul/underscore-keypath#2]
Given:
foo = {
    bar : {
        id: 0,
        name: 'foo'    
    }        
}

valueForKeyPath returns undefined for 'bar.id'.

Please see:
http://jsfiddle.net/ufn9z24L/

I might submit a pull request a fix for it later (if no one else does).

**Comment by jeeeyul** [comment]
@davidmontoyago Wow, What a shameful bug!
It'is fixed now and released for all channels. (NPM, Meteor, Bower).

Test case is located at https://github.com/jeeeyul/underscore-keypath/blob/master/test/issue2.js
