### ISSUE TITLE
Array Notation not working in Internet Explorer

### ISSUE THREAD

**Issue by namirsab** [jeeeyul/underscore-keypath#5]
Array notation returning error when:
```javascript
_.valueForKeyPath(object, ['name']);
```
logs:
`keypath must be an array or a string`

Using the meteor package it last version. 0.9.2

My user agent is:
"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; LCJB; rv:11.0) like Gecko"

**Comment by namirsab** [comment]
I found the issue:
https://github.com/jeeeyul/underscore-keypath/blob/master/lib/underscore-keypath.js#L59
In this line you are checking the name of the constructor to be Array, but actually that's not supported by IE for example.
Maybe you should check it using the _.isArray from underscore, or using `array instanceof Array`

**Comment by namirsab** [comment]
@jeeeyul  If you accept pull request I can maybe fix it if you don't have the time for that! But please, take a look
And thanks for your fantastic library :smile:

**Comment by jeeeyul** [comment]
@namirsab Sure, I will accept pull request, thanks for feedback.

**Comment by namirsab** [comment]
Ok, i will do it as soon as i can :smile:

**Comment by namirsab** [comment]
#6 Pull request created!
